# constants.py

POPULATION_SIZE = 10
NUMBER_OF_ELITE_SCHEDULES = 2
TOURNAMENT_SELECTION_SIZE = 3
MUTATION_RATE = 0.1
CROSSOVER_RATE = 0.9
MAX_GENERATIONS = 150

# Weights for penalties and rewards
HARD_CONSTRAINT_PENALTY = 1
SOFT_CONSTRAINT_PENALTY = 0.01
